#$ -S /bin/bash
#$ -q rnd.q,test.q,prod.q
#$ -cwd
#$ -V
#$ -p -1000

set

JAVA_1_7=$1
GATK_DIR=$2
KEY=$3
CODING_BED=$4
CODING_BED_MT=$5
REF_GENOME=$6
CORE_PATH=$7
PROJECT=$8
SM_TAG=$9

RIS_ID=${SM_TAG%@*}
BARCODE_2D=${SM_TAG#*@}

START_EXTRACT_SNV_CODING=`date '+%s'`

# EXTRACT SAMPLE AND FILTER ON CODING REGIONS

$JAVA_1_7/java -jar $GATK_DIR/GenomeAnalysisTK.jar \
-T SelectVariants \
-R $REF_GENOME \
-sn $SM_TAG \
--keepOriginalAC \
-selectType SNP \
-L $CODING_BED \
-L $CODING_BED_MT \
-et NO_ET \
-K $KEY \
--variant $CORE_PATH/$PROJECT/VCF/SINGLE/WHOLE_GENOME/$SM_TAG".WHOLE.GENOME.vcf" \
-o $CORE_PATH/$PROJECT/SNV/SINGLE/CODING/$SM_TAG".CODING.SNV.vcf"

END_EXTRACT_SNV_CODING=`date '+%s'`

echo 'EXTRACT_SNV_CODING,B.01.A.06,'$START_EXTRACT_SNV_CODING','$END_EXTRACT_SNV_CODING >> $CORE_PATH/$PROJECT/REPORTS/run_times.csv

